Repository leahriffell/Crate, pull requests merged in 2020-12, with the labels that each got.

#52 Add updated babel versions for setup config
  code/web/package-lock.json
  code/web/package.json
Labels: chore

#75 Add test for get user email address
  code/api/package-lock.json
  code/api/package.json
  code/api/test/users/email-test.js
Labels: backend, testing

#81 US #1 - BE - Add image column to user table in db
  code/api/src/migrations/5-user-add-image.js
  code/api/src/modules/user/model.js
  code/api/src/seeders/1-user.js
Labels: backend, database

#83 US #1 - BE - Add query and test for image for user
  code/api/src/modules/user/types.js
  code/api/src/seeders/1-user.js
  code/api/test/users/email-test.js
  code/api/test/users/image-test.js
Labels: api endpoint, backend

#84 US #1 - BE - Add mutation and test for post user's image
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/test/users/image-test.js
Labels: api endpoint, backend

#85 Test/user test nw
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/auth/AuthAdminCheck.js
  code/web/src/modules/common/api/actions.js
  code/web/src/modules/crate/api/actions.js
  code/web/src/modules/product/api/state.js
  code/web/src/modules/subscription/api/state.js
  code/web/src/modules/user/Login.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/Signup.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
  code/web/src/modules/user/test/__snapshots__/profile.test.js.snap
  code/web/src/modules/user/test/profile.test.js
  code/web/src/setup/store.js
Labels: frontend, testing

#89 Add config for test db, reorganize tests by module
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/modules/user/tests/userMutation.test.js
  code/api/src/modules/user/tests/userQuery.test.js
  code/api/test/users/email-test.js
  code/api/test/users/image-test.js
Labels: backend, database, testing

#93 Reducer testing eb
  code/web/src/modules/user/api/tests/state.test.js
Labels: frontend, testing

#91 Patch email
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/tests/userMutation.test.js
  code/api/src/modules/user/tests/userQuery.test.js
Labels: api endpoint, backend

#102 US #4 - Shipping Address queries and mutations created/updated and tested
  code/api/package-lock.json
  code/api/package.json
  code/api/src/migrations/6-user-add-description.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/tests/userMutation.test.js
  code/api/src/modules/user/tests/userQuery.test.js
  code/api/src/modules/user/types.js
  code/api/src/seeders/1-user.js
Labels: api endpoint, backend

#104 User login tests
  code/api/src/modules/user/tests/userQuery.test.js
Labels: added review comments, backend, testing

#106 Legacy Code (BE) for testing userGenders
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/tests/userMutation.test.js
  code/api/src/modules/user/tests/userQuery.test.js
Labels: backend

#108 BE Add test for legacy code for userRemove
  code/api/src/modules/user/tests/userMutation.test.js
Labels: backend

#109 Edit profile debugging eb
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/web/src/modules/user/EditProfileForm.js
  code/web/src/modules/user/Login.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/ProfilePicture.js
  code/web/src/modules/user/Signup.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
  code/web/src/modules/user/api/tests/state.test.js
  code/web/src/setup/routes/user.js
Labels: frontend, refactor

#110 Add video and project overview to readme
  README.md
Labels: documentation
